/**
 * owlPayForms.js — Configuración estática de formularios OwlPay por país de destino.
 *
 * Estos son los campos que se muestran AL USUARIO — simples y en español.
 * El backend mapea estos valores al schema de Harbor en buildOwlPayBeneficiary().
 *
 * NO usar el schema dinámico de Harbor en el frontend. Toda la traducción
 * Harbor-schema → campos de usuario ocurre en el backend.
 */

export const OWLPAY_FORMS = {

  CN: {
    title: 'Datos del beneficiario en China',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Wei Zhang',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta bancaria',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Nombre del banco',
        type: 'text',
        placeholder: 'Ej: Industrial and Commercial Bank of China',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta bancaria',
        type: 'text',
        placeholder: 'Ej: 6222021234565488',
        required: true,
        maxLength: 34,
      },
      {
        key: 'swift_code',
        label: 'Código SWIFT / BIC',
        type: 'text',
        placeholder: 'Ej: ICBKCNBJ',
        required: true,
        pattern: '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        hint: '8 u 11 caracteres en mayúsculas',
        maxLength: 11,
      },
      {
        key: 'street',
        label: 'Dirección del beneficiario',
        type: 'text',
        placeholder: 'Ej: 123 Nanjing Road',
        required: true,
        maxLength: 200,
      },
      {
        key: 'city',
        label: 'Ciudad',
        type: 'text',
        placeholder: 'Ej: Shanghai',
        required: true,
        maxLength: 80,
      },
      {
        key: 'state_province',
        label: 'Provincia',
        type: 'select',
        required: true,
        options: [
          { value: 'AH', label: 'Anhui' },
          { value: 'BJ', label: 'Beijing' },
          { value: 'CQ', label: 'Chongqing' },
          { value: 'FJ', label: 'Fujian' },
          { value: 'GD', label: 'Guangdong' },
          { value: 'GS', label: 'Gansu' },
          { value: 'GX', label: 'Guangxi' },
          { value: 'GZ', label: 'Guizhou' },
          { value: 'HA', label: 'Henan' },
          { value: 'HB', label: 'Hubei' },
          { value: 'HE', label: 'Hebei' },
          { value: 'HI', label: 'Hainan' },
          { value: 'HL', label: 'Heilongjiang' },
          { value: 'HN', label: 'Hunan' },
          { value: 'JL', label: 'Jilin' },
          { value: 'JS', label: 'Jiangsu' },
          { value: 'JX', label: 'Jiangxi' },
          { value: 'LN', label: 'Liaoning' },
          { value: 'NM', label: 'Mongolia Interior' },
          { value: 'NX', label: 'Ningxia' },
          { value: 'QH', label: 'Qinghai' },
          { value: 'SC', label: 'Sichuan' },
          { value: 'SD', label: 'Shandong' },
          { value: 'SH', label: 'Shanghai' },
          { value: 'SN', label: 'Shaanxi' },
          { value: 'SX', label: 'Shanxi' },
          { value: 'TJ', label: 'Tianjin' },
          { value: 'XJ', label: 'Xinjiang' },
          { value: 'XZ', label: 'Tíbet' },
          { value: 'YN', label: 'Yunnan' },
          { value: 'ZJ', label: 'Zhejiang' },
        ],
      },
      {
        key: 'postal_code',
        label: 'Código postal',
        type: 'text',
        placeholder: 'Ej: 200000',
        required: true,
        pattern: '^\\d{6}$',
        hint: '6 dígitos',
        maxLength: 6,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',    label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                label: 'Salario' },
          { value: 'DONATIONS',             label: 'Donaciones' },
          { value: 'EDUCATION',             label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',     label: 'Gastos de negocio' },
          { value: 'INVESTMENT',            label: 'Inversión' },
          { value: 'MEDICAL_EXPENSES',      label: 'Gastos médicos' },
          { value: 'OTHER',                 label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: '¿Es una transferencia a tu propia cuenta?',
        type: 'toggle',
        required: true,
        default: false,
      },
    ],
  },

  NG: {
    title: 'Datos del beneficiario en Nigeria',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Chidi Okeke',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Banco',
        type: 'text',
        placeholder: 'Ej: Zenith Bank',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta (NUBAN)',
        type: 'text',
        placeholder: '10 dígitos',
        required: true,
        pattern: '^\\d{10}$',
        hint: '10 dígitos exactos',
        maxLength: 10,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',    label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                label: 'Salario' },
          { value: 'DONATIONS',             label: 'Donaciones' },
          { value: 'EDUCATION',             label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',     label: 'Gastos de negocio' },
          { value: 'OTHER',                 label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: '¿Es una transferencia a tu propia cuenta?',
        type: 'toggle',
        required: true,
        default: false,
      },
    ],
  },

};

// Para países OwlPay sin configuración específica aún
export const GENERIC_OWLPAY_FORM = {
  title: 'Datos del beneficiario',
  fields: [
    {
      key: 'beneficiary_name',
      label: 'Nombre completo',
      type: 'text',
      required: true,
      maxLength: 140,
    },
    {
      key: 'account_holder_name',
      label: 'Titular de la cuenta',
      type: 'text',
      required: true,
      maxLength: 140,
    },
    {
      key: 'bank_name',
      label: 'Banco',
      type: 'text',
      required: true,
      maxLength: 140,
    },
    {
      key: 'account_number',
      label: 'Número de cuenta',
      type: 'text',
      required: true,
      maxLength: 34,
    },
    {
      key: 'swift_code',
      label: 'SWIFT / BIC',
      type: 'text',
      required: false,
      maxLength: 11,
    },
    {
      key: 'transfer_purpose',
      label: 'Propósito de la transferencia',
      type: 'select',
      required: true,
      options: [
        { value: 'FAMILY_MAINTENANCE',    label: 'Manutención familiar' },
        { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
        { value: 'SALARY',                label: 'Salario' },
        { value: 'DONATIONS',             label: 'Donaciones' },
        { value: 'EDUCATION',             label: 'Educación' },
        { value: 'BUSINESS_EXPENSES',     label: 'Gastos de negocio' },
        { value: 'OTHER',                 label: 'Otro' },
      ],
    },
    {
      key: 'is_self_transfer',
      label: '¿Cuenta propia?',
      type: 'toggle',
      required: true,
      default: false,
    },
  ],
};
