/**
 * owlPayForms.js — Configuración estática de formularios OwlPay por país de destino.
 *
 * Estos son los campos que se muestran AL USUARIO — simples y en español.
 * El backend mapea estos valores al schema de Harbor en buildOwlPayBeneficiary().
 *
 * NO usar el schema dinámico de Harbor en el frontend. Toda la traducción
 * Harbor-schema → campos de usuario ocurre en el backend.
 */

export const OWLPAY_FORMS = {

  CN: {
    title: 'Datos del beneficiario en China',
    fields: [
      // ── Datos del beneficiario ──
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        section: 'Datos del beneficiario',
        type: 'text',
        placeholder: 'Ej: Wei Zhang',
        required: true,
        maxLength: 140,
      },
      {
        key: 'beneficiary_dob',
        label: 'Fecha de nacimiento',
        section: 'Datos del beneficiario',
        type: 'date',
        required: false,
      },
      {
        key: 'beneficiary_id_doc_number',
        label: 'Número de documento',
        section: 'Datos del beneficiario',
        type: 'text',
        required: false,
        maxLength: 50,
      },

      // ── Dirección ──
      {
        key: 'street',
        label: 'Calle',
        section: 'Dirección',
        type: 'text',
        placeholder: 'Ej: 123 Nanjing Road',
        required: true,
        maxLength: 200,
      },
      {
        key: 'city',
        label: 'Ciudad',
        section: 'Dirección',
        type: 'text',
        placeholder: 'Ej: Shanghai',
        required: true,
        maxLength: 80,
      },
      {
        key: 'state_province',
        label: 'Provincia',
        section: 'Dirección',
        type: 'select',
        required: true,
        options: [
          { value: 'AH', label: 'Anhui' },          { value: 'BJ', label: 'Beijing' },
          { value: 'CQ', label: 'Chongqing' },      { value: 'FJ', label: 'Fujian' },
          { value: 'GD', label: 'Guangdong' },      { value: 'GS', label: 'Gansu' },
          { value: 'GX', label: 'Guangxi' },        { value: 'GZ', label: 'Guizhou' },
          { value: 'HA', label: 'Henan' },          { value: 'HB', label: 'Hubei' },
          { value: 'HE', label: 'Hebei' },          { value: 'HI', label: 'Hainan' },
          { value: 'HL', label: 'Heilongjiang' },   { value: 'HN', label: 'Hunan' },
          { value: 'JL', label: 'Jilin' },          { value: 'JS', label: 'Jiangsu' },
          { value: 'JX', label: 'Jiangxi' },        { value: 'LN', label: 'Liaoning' },
          { value: 'NM', label: 'Inner Mongolia' }, { value: 'NX', label: 'Ningxia' },
          { value: 'QH', label: 'Qinghai' },        { value: 'SC', label: 'Sichuan' },
          { value: 'SD', label: 'Shandong' },       { value: 'SH', label: 'Shanghai' },
          { value: 'SN', label: 'Shaanxi' },        { value: 'SX', label: 'Shanxi' },
          { value: 'TJ', label: 'Tianjin' },        { value: 'XJ', label: 'Xinjiang' },
          { value: 'XZ', label: 'Tibet' },          { value: 'YN', label: 'Yunnan' },
          { value: 'ZJ', label: 'Zhejiang' },
        ],
      },
      {
        key: 'postal_code',
        label: 'Código postal',
        section: 'Dirección',
        type: 'text',
        placeholder: 'Ej: 200000',
        required: true,
        pattern: '^\\d{6}$',
        hint: '6 dígitos',
        maxLength: 6,
      },

      // ── Datos bancarios ──
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Nombre del banco',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'ej. Industrial and Commercial Bank of China',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'Ej: 6222021234565488',
        required: true,
        maxLength: 34,
      },
      {
        key: 'swift_code',
        label: 'Código SWIFT / BIC',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'ej. ICBKCNBJ',
        required: true,
        pattern: '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        hint: '8 u 11 caracteres en mayúsculas',
        maxLength: 11,
      },

      // ── Propósito de la transferencia ──
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        section: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'MEDICAL_TREATMENT',       label: 'Tratamiento médico' },
          { value: 'HOTEL',                   label: 'Hotel' },
          { value: 'TRAVEL',                  label: 'Viaje' },
          { value: 'REPAYMENT_OF_LOANS',      label: 'Pago de préstamos' },
          { value: 'TAX_PAYMENT',             label: 'Pago de impuestos' },
          { value: 'PURCHASE_PROPERTY',       label: 'Compra de propiedad' },
          { value: 'PROPERTY_RENTAL',         label: 'Alquiler de propiedad' },
          { value: 'INSURANCE_PREMIUM',       label: 'Prima de seguro' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'ADVERTISING',             label: 'Publicidad' },
          { value: 'ROYALTY_FEES',            label: 'Regalías' },
          { value: 'ADVISOR_FEES',            label: 'Honorarios de asesor' },
          { value: 'CONSTRUCTION',            label: 'Construcción' },
          { value: 'TRANSPORTATION',          label: 'Transporte' },
          { value: 'EXPORTED_GOODS',          label: 'Bienes exportados' },
          { value: 'GENERAL_GOODS_OFFLINE',   label: 'Bienes generales' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        section: 'Propósito de la transferencia',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  IN: {
    title: 'Datos del beneficiario en India',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Rahul Sharma',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'in_account_number',
        label: 'Número de cuenta bancaria',
        type: 'text',
        placeholder: 'Ej: 012345678901',
        required: true,
        maxLength: 18,
      },
      {
        key: 'in_ifsc_code',
        label: 'Código IFSC',
        type: 'text',
        placeholder: 'Ej: HDFC0001234',
        required: true,
        pattern: '^[A-Z]{4}0[A-Z0-9]{6}$',
        hint: '11 caracteres: 4 letras + 0 + 6 alfanuméricos',
        maxLength: 11,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'EXPORTED_GOODS',          label: 'Bienes exportados' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: '¿Es una transferencia a tu propia cuenta?',
        type: 'toggle',
        required: true,
        default: false,
      },
    ],
  },

  NG: {
    title: 'Datos del beneficiario en Nigeria',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Chidi Okeke',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Banco',
        type: 'text',
        placeholder: 'Ej: Zenith Bank',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta (NUBAN)',
        type: 'text',
        placeholder: '10 dígitos',
        required: true,
        pattern: '^\\d{10}$',
        hint: '10 dígitos exactos',
        maxLength: 10,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',    label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                label: 'Salario' },
          { value: 'DONATIONS',             label: 'Donaciones' },
          { value: 'EDUCATION',             label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',     label: 'Gastos de negocio' },
          { value: 'OTHER',                 label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: '¿Es una transferencia a tu propia cuenta?',
        type: 'toggle',
        required: true,
        default: false,
      },
    ],
  },

  EU: {
    title: 'Datos del beneficiario en Europa (SEPA)',
    fields: [
      // ── Datos del beneficiario ──
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        section: 'Datos del beneficiario',
        type: 'text',
        placeholder: 'Ej: Hans Müller',
        required: true,
        maxLength: 140,
      },
      {
        key: 'beneficiary_dob',
        label: 'Fecha de nacimiento',
        section: 'Datos del beneficiario',
        type: 'date',
        required: true,
        hint: 'Requerido por regulación europea (AML)',
      },
      {
        key: 'beneficiary_id_doc_number',
        label: 'Número de pasaporte o documento de identidad',
        section: 'Datos del beneficiario',
        type: 'text',
        required: true,
        maxLength: 50,
        hint: 'Requerido por regulación europea (AML)',
      },

      // ── Dirección del beneficiario ──
      {
        key: 'street',
        label: 'Calle y número',
        section: 'Dirección',
        type: 'text',
        placeholder: 'Ej: Hauptstraße 15',
        required: true,
        maxLength: 200,
      },
      {
        key: 'city',
        label: 'Ciudad',
        section: 'Dirección',
        type: 'text',
        placeholder: 'Ej: Berlín',
        required: true,
        maxLength: 80,
      },
      {
        key: 'postal_code',
        label: 'Código postal',
        section: 'Dirección',
        type: 'text',
        placeholder: 'Ej: 10115',
        required: true,
        maxLength: 10,
      },

      // ── Datos bancarios ──
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'iban',
        label: 'IBAN',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'Ej: DE89370400440532013000',
        required: true,
        pattern: '^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$',
        hint: 'Código IBAN del banco europeo (15–34 caracteres)',
        maxLength: 34,
      },
      {
        key: 'bic',
        label: 'BIC / SWIFT',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'Ej: DEUTDEDB',
        required: true,
        pattern: '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        hint: '8 u 11 caracteres en mayúsculas',
        maxLength: 11,
      },
      {
        key: 'bank_name',
        label: 'Nombre del banco',
        section: 'Datos bancarios',
        type: 'text',
        placeholder: 'Ej: Deutsche Bank',
        required: false,
        maxLength: 140,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'ADVISOR_FEES',            label: 'Honorarios profesionales' },
          { value: 'PROPERTY_RENTAL',         label: 'Alquiler de propiedad' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  BR: {
    title: 'Datos del beneficiario en Brasil',
    hint: 'El beneficiario recibirá el dinero vía PIX — instantáneo a cualquier banco brasileño.',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: João Silva',
        required: true,
        maxLength: 140,
      },
      {
        key: 'pix_key_type',
        label: 'Tipo de chave PIX',
        type: 'select',
        required: true,
        options: [
          { value: 'cpf',     label: 'CPF (documento de identidad)' },
          { value: 'email',   label: 'Email' },
          { value: 'phone',   label: 'Teléfono celular' },
          { value: 'random',  label: 'Chave aleatória' },
          { value: 'account', label: 'Cuenta bancaria' },
        ],
      },
      {
        key: 'br_pix_key',
        label: 'Chave PIX',
        type: 'text',
        placeholder: 'Ingresa la chave PIX del beneficiario',
        required: true,
        maxLength: 77,
        hint: 'CPF: 000.000.000-00 · Email · +55 11 99999-9999 · UUID',
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  MX: {
    title: 'Datos del beneficiario en México',
    hint: 'La transferencia llega vía SPEI — el sistema interbancario instantáneo de México.',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: María García',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        placeholder: 'Nombre como aparece en el banco',
        required: true,
        maxLength: 140,
      },
      {
        key: 'mx_clabe',
        label: 'CLABE interbancaria',
        type: 'text',
        placeholder: 'Ej: 646180157000000004',
        required: true,
        pattern: '^\\d{18}$',
        hint: '18 dígitos — la encuentras en tu app bancaria o estado de cuenta',
        maxLength: 18,
      },
      {
        key: 'bank_name',
        label: 'Banco (opcional)',
        type: 'text',
        placeholder: 'Ej: BBVA México, Banamex',
        required: false,
        maxLength: 140,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  AE: {
    title: 'Datos del beneficiario en Emiratos Árabes',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Ahmed Al Rashidi',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        required: true,
        maxLength: 140,
      },
      {
        key: 'iban',
        label: 'IBAN',
        type: 'text',
        placeholder: 'Ej: AE070331234567890123456',
        required: true,
        pattern: '^AE\\d{21}$',
        hint: '23 caracteres — empieza con AE',
        maxLength: 23,
      },
      {
        key: 'bank_name',
        label: 'Banco (opcional)',
        type: 'text',
        placeholder: 'Ej: Emirates NBD, ADCB',
        required: false,
        maxLength: 140,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'EXPORTED_GOODS',          label: 'Bienes exportados' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  GB: {
    title: 'Datos del beneficiario en Reino Unido',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: James Smith',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        required: true,
        maxLength: 140,
      },
      {
        key: 'sort_code',
        label: 'Sort Code',
        type: 'text',
        placeholder: 'Ej: 20-00-00',
        required: true,
        pattern: '^\\d{2}-?\\d{2}-?\\d{2}$',
        hint: '6 dígitos en formato 00-00-00',
        maxLength: 8,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta',
        type: 'text',
        placeholder: 'Ej: 12345678',
        required: true,
        pattern: '^\\d{8}$',
        hint: '8 dígitos exactos',
        maxLength: 8,
      },
      {
        key: 'bank_name',
        label: 'Banco (opcional)',
        type: 'text',
        placeholder: 'Ej: Barclays, HSBC, Lloyds',
        required: false,
        maxLength: 140,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  JP: {
    title: 'Datos del beneficiario en Japón',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo (en romaji)',
        type: 'text',
        placeholder: 'Ej: Tanaka Hiroshi',
        required: true,
        maxLength: 140,
        hint: 'Usar letras latinas (romaji), no kanji',
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta (en romaji)',
        type: 'text',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Banco',
        type: 'text',
        placeholder: 'Ej: MUFG Bank, Sumitomo Mitsui',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta',
        type: 'text',
        placeholder: 'Ej: 1234567',
        required: true,
        maxLength: 20,
      },
      {
        key: 'swift_code',
        label: 'SWIFT / BIC',
        type: 'text',
        placeholder: 'Ej: BOTKJPJT',
        required: true,
        pattern: '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        hint: '8 u 11 caracteres en mayúsculas',
        maxLength: 11,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'EXPORTED_GOODS',          label: 'Bienes exportados' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  SG: {
    title: 'Datos del beneficiario en Singapur',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Lee Wei Ming',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Banco',
        type: 'text',
        placeholder: 'Ej: DBS Bank, OCBC, UOB',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta',
        type: 'text',
        placeholder: 'Ej: 1234567890',
        required: true,
        maxLength: 20,
      },
      {
        key: 'swift_code',
        label: 'SWIFT / BIC',
        type: 'text',
        placeholder: 'Ej: DBSSSGSG',
        required: true,
        pattern: '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        maxLength: 11,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  HK: {
    title: 'Datos del beneficiario en Hong Kong',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: Chan Tai Man',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        required: true,
        maxLength: 140,
      },
      {
        key: 'bank_name',
        label: 'Banco',
        type: 'text',
        placeholder: 'Ej: HSBC HK, Hang Seng Bank',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta',
        type: 'text',
        placeholder: 'Ej: 123-456789-001',
        required: true,
        maxLength: 20,
      },
      {
        key: 'swift_code',
        label: 'SWIFT / BIC',
        type: 'text',
        placeholder: 'Ej: HSBCHKHHHKH',
        required: true,
        pattern: '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        maxLength: 11,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'EXPORTED_GOODS',          label: 'Bienes exportados' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

  US: {
    title: 'Datos del beneficiario en Estados Unidos',
    hint: 'La transferencia llega vía ACH — el sistema bancario electrónico de EEUU (2-5 días hábiles).',
    fields: [
      {
        key: 'beneficiary_name',
        label: 'Nombre completo',
        type: 'text',
        placeholder: 'Ej: John Smith',
        required: true,
        maxLength: 140,
      },
      {
        key: 'account_holder_name',
        label: 'Titular de la cuenta',
        type: 'text',
        required: true,
        maxLength: 140,
      },
      {
        key: 'routing_number',
        label: 'Routing Number (ABA)',
        type: 'text',
        placeholder: 'Ej: 021000021',
        required: true,
        pattern: '^\\d{9}$',
        hint: '9 dígitos — lo encuentras en tus cheques o app bancaria',
        maxLength: 9,
      },
      {
        key: 'account_number',
        label: 'Número de cuenta',
        type: 'text',
        placeholder: 'Ej: 123456789',
        required: true,
        maxLength: 17,
      },
      {
        key: 'account_type',
        label: 'Tipo de cuenta',
        type: 'select',
        required: true,
        options: [
          { value: 'checking', label: 'Checking (corriente)' },
          { value: 'savings',  label: 'Savings (ahorro)' },
        ],
      },
      {
        key: 'bank_name',
        label: 'Banco (opcional)',
        type: 'text',
        placeholder: 'Ej: Chase, Bank of America, Wells Fargo',
        required: false,
        maxLength: 140,
      },
      {
        key: 'transfer_purpose',
        label: 'Propósito de la transferencia',
        type: 'select',
        required: true,
        options: [
          { value: 'FAMILY_MAINTENANCE',      label: 'Manutención familiar' },
          { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
          { value: 'SALARY',                  label: 'Salario' },
          { value: 'EDUCATION',               label: 'Educación' },
          { value: 'BUSINESS_EXPENSES',       label: 'Gastos de negocio' },
          { value: 'OTHER',                   label: 'Otro' },
        ],
      },
      {
        key: 'is_self_transfer',
        label: 'Esta cuenta me pertenece',
        type: 'toggle',
        required: false,
        default: false,
      },
    ],
  },

};

// Para países OwlPay sin configuración específica aún
export const GENERIC_OWLPAY_FORM = {
  title: 'Datos del beneficiario',
  fields: [
    {
      key: 'beneficiary_name',
      label: 'Nombre completo',
      type: 'text',
      required: true,
      maxLength: 140,
    },
    {
      key: 'account_holder_name',
      label: 'Titular de la cuenta',
      type: 'text',
      required: true,
      maxLength: 140,
    },
    {
      key: 'bank_name',
      label: 'Banco',
      type: 'text',
      required: true,
      maxLength: 140,
    },
    {
      key: 'account_number',
      label: 'Número de cuenta',
      type: 'text',
      required: true,
      maxLength: 34,
    },
    {
      key: 'swift_code',
      label: 'SWIFT / BIC',
      type: 'text',
      required: false,
      maxLength: 11,
    },
    {
      key: 'transfer_purpose',
      label: 'Propósito de la transferencia',
      type: 'select',
      required: true,
      options: [
        { value: 'FAMILY_MAINTENANCE',    label: 'Manutención familiar' },
        { value: 'TRANSFER_TO_OWN_ACCOUNT', label: 'Transferencia a cuenta propia' },
        { value: 'SALARY',                label: 'Salario' },
        { value: 'DONATIONS',             label: 'Donaciones' },
        { value: 'EDUCATION',             label: 'Educación' },
        { value: 'BUSINESS_EXPENSES',     label: 'Gastos de negocio' },
        { value: 'OTHER',                 label: 'Otro' },
      ],
    },
    {
      key: 'is_self_transfer',
      label: '¿Cuenta propia?',
      type: 'toggle',
      required: true,
      default: false,
    },
  ],
};
